### ISSUE TITLE
안녕하세요! 성경구절 오류 질문입니다!

### ISSUE THREAD

**Issue by Jeong-Kwang-Eun** [sunghwan2789/Bible2PPT#100]
안녕하세요!
Bible2PPT를 잘 사용하고 있는 사람입니다.
좋은 프로그램 만들어주셔서 감사합니다.

어제까지만 해도 프로그램이 잘 작동했는데
오늘 실행해서 해보려 하니 성경구절ppt가 만들어지지 않고 있습니다.
프로그램 문제인가해서 지웠다 다시 깔아보기도 하고 컴터도 껐다 켰는데
입력은 되는데 ppt가 만들어지지 않네요.

혹시나 하는 마음에 다른 컴퓨터로도 시도해보았는데 ppt가 만들어지지 않습니다
다른 부분이 있다면 새롭게 까니 윈도우디펜더?에서 실행할거냐고 물어보기는 했습니다!

3개 컴퓨터에서 해보았는데 실행은 되는데 성경구절 입력하고 ppt 만들면 템플릿만 보이네요ㅠㅠ
두 컴퓨터는 ppt가 아예 안만들어지고 
한 컴퓨터는 성경이름 장 절은 되는데 구절[바디]부분이 아무것도 안써져 있습니다!

원인을 몰라 혹시나해서 여기에 여쭤봅니다!

**Comment by sunghwan2789** [comment]
어떤 성경을 사용하셨나요? 만들기 할 때 넣은 성경 구절도 올려주세요~

2022년 4월 14일 (목) 18:23, Jeong-Kwang-Eun ***@***.***>님이 작성:

**Comment by Jeong-Kwang-Eun** [comment]
네 첨에는 사도행전 1장 6-11절 (행1:6-11)로 시도해서
안되어가지고 창세기 1장(창1) 했다가
창세기1장 1-11절(창1:1-11)도 해보고
마태복음1장 1-5절(마1:1-5)도 해보았습니다!

**Comment by sunghwan2789** [comment]
https://github.com/sunghwan2789/Bible2PPT/issues/99#issuecomment-1099662226 참고해주세요

**Comment by Jeong-Kwang-Eun** [comment]
네 확인했어요!
저만 그런게 아니었군요!
감사합니다!!

**Comment by sunghwan2789** [comment]
#99 참고해주세요.

2022년 4월 14일 (목) 19:21, Jeong-Kwang-Eun ***@***.***>님이 작성:
