### ISSUE TITLE
-

### ISSUE THREAD

**Issue by HANNAH7012** [sunghwan2789/Bible2PPT#107]

**Comment by sunghwan2789** [comment]
평소에 사용하지 않던 성경 소스로 PPT를 만들면, 초기에 데이터를 받는 시간이 걸리기 때문에 느리게 느낄 수 있어요.

2023년 2월 14일 (화) 15:30, HANNAH7012 ***@***.***>님이 작성:

**Comment by sunghwan2789** [comment]
또, 여러 PPT를 동시에 만드는 건 기술적으로 어려워서, 한 PPT를 만드는 중이면 나머지는 대기 중으로 있어요.

2023년 2월 14일 (화) 19:35, 방성환 ***@***.***>님이 작성:
