### ISSUE TITLE
바이블2ppt 생성 오류문의

### ISSUE THREAD

**Issue by Daekwang1** [sunghwan2789/Bible2PPT#108]
안녕하세요, 우선 바이블2ppt를 만들어 주심에 진심으로 감사드립니다

3년전쯤부터 해당 프로그램을 유용하게 잘 사용하고 있었습니다.

그런데 최근에 갑작스레 성경구절 생성이 안된는 현상이 발생되었습니다.

구버전포함 신버전도 마찬가지로 되지않고있으며,
기존 프로그램 실행시 좌측편에 성경 절(ex. 창세기, 출애굽기 등)이 표시되었었지만, 현재 오류발생시점부터는
해당 절이 표기가 안되고있는 상황입니다.

일전에 다른 분이 올린 이슈에대해 읽어보았고 같은현상으로 파악이되며,
ppt는 최신버전이고, vba또한 설치가 되어있습니다.

혹시나 개역개정이 아닌 다른 번역성경도 되나 실험을 해보았지만 마찬가지로 안되는 현상이 보이고 있습니다.

안되는 장면을 사진으로 첨부하여 올립니다. 확인한번 부탁드리겠습니다.

![KakaoTalk_20230215_215428731](https://user-images.githubusercontent.com/125466227/219033095-5a8a5c0d-876b-4f0c-903d-4634c976e49f.jpg)
![KakaoTalk_20230215_215428731_01](https://user-images.githubusercontent.com/125466227/219033105-b5e10241-752f-4757-a50e-9ab7a492e216.jpg)
![KakaoTalk_20230215_215428731_02](https://user-images.githubusercontent.com/125466227/219033107-a368c327-f0a1-4dfc-8394-7964d170ec5b.jpg)
![KakaoTalk_20230215_215428731_03](https://user-images.githubusercontent.com/125466227/219033109-bf6935c5-0f28-47be-9d5f-2f8d1b2c2262.jpg)
![KakaoTalk_20230215_215428731_04](https://user-images.githubusercontent.com/125466227/219033111-9540d935-c458-4c8d-94ad-7e23dc51784d.jpg)
![KakaoTalk_20230215_215428731_05](https://user-images.githubusercontent.com/125466227/219033117-65b8694e-8c86-4270-b6f6-4028b0a4fe5c.jpg)

**Comment by sunghwan2789** [comment]
#106 중복 이슈가 있으니 참고하시고, 다른 성경 소스를 이용해주세요~
