### ISSUE TITLE
한글 영어 두 가지 성경 표시 방법 좀 알려주세요

### ISSUE THREAD

**Issue by phil0717** [sunghwan2789/Bible2PPT#121]
안녕하세요 Bible2ppt 프로그램 잘 사용하고 있습니다. 

한 가지 질문이 있는데요, 
한글과 영어 두 가지 번역본을 한 페이지에 출력할 수 있는 방법 알려주시면 감사하겠습니다. 
제가 하니까 한글만 출력되고 있어서요.. 
감사합니다. 

![image](https://github.com/user-attachments/assets/2e33053d-9b61-416e-b5ce-b5a2d98c8725)
![image](https://github.com/user-attachments/assets/9fa32d77-8194-4885-a581-503600951d52)

**Comment by digitallee88** [comment]
![스크린샷 2024-09-18 094859](https://github.com/user-attachments/assets/96f9e455-69a0-4cd0-9a77-92f0adc7a4b8)
템플릿 편집하기에서 이런 식으로 하면 되는거 같습니다.

BODY1 이 개역개정
BODY2 가 NIV
이런식인거 같습니다.

**Comment by junodite** [comment]
윗분 내용이 맞습니다.
저희도 이렇게 잘 사용하고 있습니다.
![Uploading 2024-09-20001.jpg…]()

**Comment by phil0717** [comment]
답변 주신 분들 모두 감사드립니다. 
잘 작동하네요.
