### ISSUE TITLE
한 페이지에 여러 성경을 사용하는 기능

### ISSUE THREAD

**Issue by sunghwan2789** [sunghwan2789/Bible2PPT#15]
FROM http://blog.bloodcat.com/278#comment12186298
> 전주현
2018.03.04 11:37
안녕하세요. 교회에 외국인 성도님들이 찾아오시기 시작하여 성경 한글과 영어를 같이 띄워드리려고 하는데
이 프로그램을 이용해서 한 화면에 같이 띄어드릴수 있을까요?

**Comment by sunghwan2789** [comment]
+1

**Comment by chn2128** [comment]
안녕하세요. 러시아에 있는 학생입니다. 같은 의견에 러시아어 성경 추가도 가능할까요?

**Comment by sunghwan2789** [comment]
러시아 성경 사이트가 있으면 알려주세요~

2019년 6월 10일 (월) 15:37, chn2128 <notifications@github.com>님이 작성:

**Comment by chn2128** [comment]
https://bible-teka.com/

사이트 추가 했습니다~

**Comment by sunghwan2789** [comment]
유승원
2019.01.09 23:54 신고 [Edit/Del] [Reply]
안녕하세요.
늘 감사하게 잘 사용하고 있습니다.
몇몇분들이 말씀하시는 것 중에 영어성경에 관해서 문의 드립니다.
저희 교회도 이번에 영어통역예배를 드리게 되어 예배중에 성경말씀을 한글과 영어를 동시에 띄우게 되었습니다.
그래서 지금은 탬플릿을 2개로 만들어서 한글은 윗쪽으로 정렬되게 하고 영어는 아래쪽으로 정렬되게 하여 각각 만든 후 만든것을 열어서 하나로 합치고 있습니다.

![http://haebang.or.kr/upload_data/bbs/sermon05/bbs_6192687950.jpg](http://haebang.or.kr/upload_data/bbs/sermon05/bbs_6192687950.jpg)
위의 이미지처럼요...

이런 탬플릿이라면 프로그램을 크게 수정하지 않고 가능하지 않을까 생각되기도 해서요...
물론 한절이 많아져서 한화면에 다 안들어가는것도 있겠지만.. 그것은 별도로 수정하면 되는것이니..
혹시 이렇게 한번에 한글과 영어 2개의 디비를 불러와서 넣을수 있도록 가능할까요?

물론 지금 프로그램만으로도 너무 감사하고 잘 사용하고 있습니다.
혹시 한영에 대해 생각하시는 바가 있으신가 해서 여쭤봅니다.
늘 감사합니다.^^
