### ISSUE TITLE
ppt만들기하면 오류가... ㅠㅠ

### ISSUE THREAD

**Issue by Lee-Boram** [sunghwan2789/Bible2PPT#99]
ppt 만들기를 하면 이런 오류가 나는데
지우고 새로 설치해도 이렇습니다
System.InvalidOperationException: 시퀀스에 요소가 없습니다.
   위치: System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   위치: Bible2PPT.Services.BibleService.<>c__DisplayClass9_0.<GetVersesAsync>g__Cache|3()
   위치: Bible2PPT.Services.BibleService.<GetVersesAsync>d__9.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   위치: Bible2PPT.Services.ZippedBibleService.<GetEachVersesAsync>d__7.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Bible2PPT.Services.ZippedBibleService.<GetVersesAsync>d__8.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   위치: System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   위치: System.Linq.AsyncEnumerable.WhereEnumerableAsyncIterator`1.<MoveNextCore>d__8.MoveNext() 파일 /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Where.cs:줄 213
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Linq.AsyncIteratorBase`1.<MoveNextAsync>d__8.MoveNext() 파일 /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:줄 70
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   위치: System.Linq.AsyncIteratorBase`1.<MoveNextAsync>d__8.MoveNext() 파일 /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:줄 75
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   위치: Bible2PPT.PPT.PPTManager.<AppendChapter>d__13.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   위치: Bible2PPT.PPT.PPTManager.<AppendChapter>d__13.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   위치: Bible2PPT.PPT.Builder.<ProcessAsync>d__11.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Bible2PPT.PPT.JobManager.<>c__DisplayClass9_0.<<Queue>b__0>d.MoveNext()

**Comment by sunghwan2789** [comment]
어떤 성경을 선택하셨나요?

2022년 4월 14일 (목) 12:49, Lee-Boram ***@***.***>님이 작성:

**Comment by Lee-Boram** [comment]
갓피플성경.개역성경 이었어요
개역성경, 쉬운성경 두개였는데.

2022년 4월 14일 (목) 오후 6:05, Sunghwan Bang ***@***.***>님이 작성:

**Comment by Lee-Boram** [comment]
어제 윈도우즈 업데이트 한 것이 영향이 있지 않았나 하는 생각이 듭니다. 
여러 컴에서 해봤는데 다 증상이 똑같아요

**Comment by sunghwan2789** [comment]
갓피플이 성경을 비공개로 전환했네요. 다른 소스를 사용해주세요ㅠ
차기 버전에서 제거해야겠어요

**Comment by sunghwan2789** [comment]
다시 잘 되네요.

갓피플 웹서버에 https를 적용하면서 생긴 일시적인 오류로, 현재는 해결된 것으로 보이니까 이슈는 닫도록 하겠습니다~

**Comment by sunghwan2789** [comment]
갓피플이 성경을 비공개로 전환했네요. 다른 소스를 사용해주세요ㅠ

2022년 4월 14일 (목) 20:03, Lee-Boram ***@***.***>님이 작성:
